### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by louisRobert** [PredictiveEcology/SpaDES.shiny#105] opened 2020-03-26 17:18 UTC
Java SDK version is 14.0.0.0 (64 bit). This is mishandling version information upon installation verification ( I think) and might be interpreting only the 0.0.0  

error: Your java version is 14.  Need 1.5.0 or higher.
Execution halted
ERROR: lazy loading failed for package 'SpaDES.shiny'

*** full console****
```r
> install_github("PredictiveEcology/SpaDES.shiny", dependencies = TRUE)
Downloading GitHub repo PredictiveEcology/SpaDES.shiny@master

√  checking for file 'C:\Users\Louis\AppData\Local\Temp\RtmpO8wyBE\remotes2f781aab7234\PredictiveEcology-SpaDES.shiny-9aca88d/DESCRIPTION' ... 
-  preparing 'SpaDES.shiny':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'SpaDES.shiny/man-roxygen'
-  building 'SpaDES.shiny_0.2.0.tar.gz'
   
Installing package into ‘C:/Users/Louis/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'SpaDES.shiny' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'xlsx', details:
  call: fun(libname, pkgname)
  error: Your java version is 14.  Need 1.5.0 or higher.
Execution halted
ERROR: lazy loading failed for package 'SpaDES.shiny'
* removing 'C:/Users/Louis/Documents/R/win-library/3.6/SpaDES.shiny'
Error: Failed to install 'SpaDES.shiny' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Louis/AppData/Local/Temp/RtmpO8wyBE/file2f781f1f2f86/SpaDES.shiny_0.2.0.tar.gz’ had non-zero exit status
```

**Comment by achubaty** [comment] 2020-03-26 17:20
How did you install Java? And have you done `R CMD javareconf` from the commandline?

**Comment by louisRobert** [comment] 2020-03-26 17:43
Both from windows installer JRE 8u241 and JDK-14 (both 64 bit). No command line. I do not think `R CMD javareconf` works in windows setting it looks more like a UNIX command but i might be wrong. RJava was installed through install.packages()

**Comment by achubaty** [comment] 2020-03-26 18:20
can you confirm that you can load `rJava`?

```r
library(rJava)
```

**Comment by achubaty** [comment] 2020-03-26 18:21
maybe also try reinstalling that package to make sure it picks up the java update

**Comment by louisRobert** [comment] 2020-03-27 18:07
RJava load with no problems, I tried reinstalling RJava, same error message

**Comment by achubaty** [comment] 2020-03-29 16:08
sorry, to be clear, when you reinstalled `rJava`, you had no problem loading it? the problem is still with the `SpaDES.shiny` install? Can you load `xlsx`?

**Comment by louisRobert** [comment] 2020-04-13 11:39
I apologise for the long delay, I fiddled a lot with your comment and it seems that the culprit is xlsx which i was not able to load. The issue was fixed https://github.com/colearendt/xlsx/issues/128 in the development version.

**Comment by achubaty** [comment] 2020-04-13 14:09
thanks for following up. closing.

**Closed as completed by achubaty** 2020-04-13 14:09 UTC
